env:
  browser: true
  es6: true
extends:
  - "airbnb"
  - "plugin:react/recommended"
  - "plugin:@typescript-eslint/recommended"

parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - react-hooks
  - "@typescript-eslint"
  - "prettier"
rules:
  {
    "prettier/prettier": "error",
    "react-hooks/rules-of-hooks": "error",
    "no-use-before-define": "off",
    "react/require-default-props": "off",
    "react/react-in-jsx-scope": "off",
    "react/jsx-props-no-spreading": "off",
    "react-hooks/exhaustive-deps": "warn",
    "eslint no-use-before-define": "off",
    "eslint operator-linebreak": " [ 'error', 'after']",
    "react/jsx-filename-extension": "off",
    "import/prefer-default-export": "off",
    "import/extensions":
      ["error", "ignorePackages", { "ts": "never", "tsx": "never" }],
    "@typescript-eslint/explicit-module-boundary-types": "off",
  }
settings: { "import/resolver": { "typescript": {} } }
